mappings:
  DiscountCouponSiteTreeDOD_Field: Sunnysideup\EcommerceDiscountCoupon\Form\DiscountCouponSiteTreeDOD_Field
  DiscountCouponModifier_Form: Sunnysideup\EcommerceDiscountCoupon\Modifiers\DiscountCouponModifierForm
  DiscountCouponModifier: Sunnysideup\EcommerceDiscountCoupon\Modifiers\DiscountCouponModifier
  DiscountCouponFilterForDate: Sunnysideup\EcommerceDiscountCoupon\Search\DiscountCouponFilterForDate
  DiscountCouponProductDataExtension: Sunnysideup\EcommerceDiscountCoupon\Model\Buyables\DiscountCouponProductDataExtension
  DiscountCouponSiteTreeDOD_ProductVariation: Sunnysideup\EcommerceDiscountCoupon\Model\Buyables\DiscountCouponSiteTreeDODProductVariation
  DiscountCouponSiteTreeDOD: Sunnysideup\EcommerceDiscountCoupon\Model\Buyables\DiscountCouponSiteTreeDOD
  DiscountCouponSiteTreeDOD_Product: Sunnysideup\EcommerceDiscountCoupon\Model\Buyables\DiscountCouponSiteTreeDODProduct
  DiscountCouponOption: Sunnysideup\EcommerceDiscountCoupon\Model\DiscountCouponOption
